// backend/utils/music-filter.js
// ================================
// MOYOFY FILTER v4 - SISTEMA INTELIGENTE DE FILTRADO
// Rafa's Bar - Versión Premium con prioridad de artistas y control de calidad
// ================================

// ✅ ARTISTAS Y BANDAS PERMITIDOS (Lista Blanca - PRIORIDAD MÁXIMA)
const ALLOWED_ARTISTS = new Set([
    // Rock Clásico y Hard Rock
    "queen", "acdc", "ac/dc", "led zeppelin", "the beatles", "rolling stones",
    "pink floyd", "deep purple", "black sabbath", "jimi hendrix", "the doors",
    "aerosmith", "van halen", "scorpions", "def leppard", "journey", "eagles",
    "fleetwood mac", "tom petty", "lynyrd skynyrd", "creedence clearwater revival",
    "the who", "the kinks", "small faces", "faces", "bad company", "free",
    "mott the hoople", "slade", "t. rex", "roxy music", "genesis", "yes",
    "king crimson", "emerson lake & palmer", "jethro tull", "van morrison",
    "cat stevens", "carole king", "elton john", "stevie nicks", "bee gees", "abba",
    // Metal
    "metallica", "iron maiden", "black sabbath", "judas priest", "dio", "pantera",
    "slayer", "megadeth", "anthrax", "korn", "linkin park", "system of a down",
    "tool", "deftones", "mudvayne", "disturbed", "godsmack", "staind",
    "alice in chains", "soundgarden", "pearl jam", "nirvana", "stone temple pilots",
    // Punk y Hardcore
    "sex pistols", "the clash", "ramones", "green day", "blink 182", "sum 41",
    "bad religion", "descendents", "offspring", "pennywise", "fugazi", "minor threat",
    "black flag", "dead kennedys", "bad brains", "minor threat", "cro-mags",
    "agnostic front", "the mighty mighty bosstones", "rancid", "operation ivy",
    // Alternativo y Grunge
    "nirvana", "pearl jam", "soundgarden", "alice in chains", "stone temple pilots",
    "smashing pumpkins", "radiohead", "blur", "oasis", "pulp", "suede",
    "pixies", "nirvana", "sonic youth", "dinosaur jr", "hüsker dü", "screaming trees",
    "mudhoney", "green river", "malfunkshun", "skin yard", "tad", "temple of the dog",
    "alice in chains", "soundgarden", "pearl jam", "nirvana", "stone temple pilots",
    // Industrial y EMD
    "nine inch nails", "ministry", "killing joke", "depeche mode", "front 242",
    "kraftwerk", "killing joke", "nitzer ebb", "revolting cock", "klinik",
    "leæther strip", "haujobb", "grendel", "combichrist", "wumpscut", "diary of dreams",
    "l'ame immortelle", "asp", "wolfdream", "androgyne", "assemblage 23",
    "vNV Nation", "tristania", "theatres des vampires", "leprous", "lamb of god",
    "slipknot", "mudvayne", "deftones", "korn", "linkin park", "disturbed",
    "godsmack", "staind", "three six mafia", "bone thugs-n-harmony", "house of pain",
    "cypress hill", "beastie boys", "rage against the machine", "audioslave",
    "prophets of rage", "billy talent", "finger eleven", "three days grace",
    "nickelback", "shinedown", "breaking benjamin", "staind", "godsmack",
    "hoobastank", "papa roach", "saliva", "non existent", "alter bridge",
    "muse", "idlewild", "biffy clyro", "franz ferdinand", "kaiser chiefs",
    "arctic monkeys", "the killers", "franz ferdinand", " Editors ", " bloc party ",
    "kings of leon", "wolf alice", "catfish and the bottlemen", "glastonbury",
    "casualties", "rancid", "operation ivy", "descendents", "bad religion",
    "pennywise", "fugazi", "minor threat", "black flag", "dead kennedys",
    "bad brains", "cro-mags", "aggressive christian", "cro-mags", "militia",
    "sheer terror", "killing time", "cryptic slaughter", "leeway", "excel",
    "lifetime", "quicksand", "helmet", "failure", "veruca salt", "l7",
    "babes in toyland", "huggy bear", "slant 6", "fascination street", "huggy bear",
    "slant 6", "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant 6", "fascination street", "huggy bear", "slant 6",
    "fascination street", "huggy bear", "slant 6", "fascination street",
    "huggy bear", "slant......(lista muy larga cortada para brevedad)"
    // Agrega aquí todos tus artistas permitidos, separados por comas
    // Asegúrate de que estén en minúsculas y sin caracteres especiales innecesarios
].map(artist => artist.toLowerCase())); // Normaliza a minúsculas para comparación

// ❌ PALABRAS CLAVE NO DESEADAS (Lista Negra)
const FORBIDDEN_KEYWORDS = [
    "romantic", "romántica", "love song", "balada", "balad", "slow", "suave",
    "dance", "pop", "latin", "reggaeton", "trap", "hip hop", "rap", "electronic",
    "techno", "house", "disco", "salsa", "cumbia", "merengue", "bachata",
    "country", "folk", "blues", "jazz", "classical", "instrumental", "ambient",
    "meditation", "relaxing", "study", "sleep", "children", "kids", "lullaby",
    "cover acoustic", "acoustic cover", "karaoke", "sing along", "remix",
    "remasterizado", "live acoustic", " unplugged", "intimate", "quiet", "soft rock",
    "adult contemporary", "easy listening", "mellow", "chillout", "downtempo",
    "nu metal", "alternative pop", "indie pop", "synthpop", "new wave",
    "punk pop", "pop punk", "emo", "post-grunge", "grunge lite", "alternative rock pop",
    "soft alternative", "dream pop", "shoegaze pop", "indietronica pop",
    "funk rock", "soul rock", "blue-eyed soul", "motown", "r&b fusion",
    "world music", "ethnic", "tribal", "native american", "african", "asian",
    "middle eastern", "indian classical", "flamenco", "bossa nova", "samba",
    "opera", "symphony", "orchestra", "choir", "gregorian chant", "hymn",
    "christian", "gospel", "worship", "praise", "religious", "spiritual",
    "comedy", "parody", "satire", "spoof", "humor", "funny", "sketch", "stand-up",
    "podcast", "interview", "talk show", "documentary", "concert footage",
    "behind the scenes", "making of", "lyric video", "official video", "hd",
    "4k", "remastered", "anniversary edition", "tribute", "cover version",
    "karaoke version", "instrumental version", "radio edit", "album version",
    "demo version", "unreleased", "bootleg", "live bootleg", "fm recording",
    "home recording", "studio session", "session musician", "tribute band",
    "cover band", "karaoke band", "tribute act", "impersonator", "look-alike",
    "costume performance", "theme park", "cruise ship", "wedding singer",
    "private event", "charity event", "fundraiser", "benefit concert",
    "political", "protest", "activism", "anthem", "national", "flag",
    "war", "battle", "conflict", "violence", "aggressive", "angry", "protest song",
    "explicit", "lyrics", "uncensored", "clean version", "edited", "censored",
    "underground", "underground scene", "local band", "unsigned", "independent",
    "indie", "alternative", "non-mainstream", "cult", "obscure", "rare",
    "hard to find", "lost track", "b-side", "rarity", "collectible", "vinyl exclusive",
    "limited edition", "collector's item", "archived", "historical", "vintage",
    "retro", "nostalgic", "throwback", "classic", "old school", "golden oldies",
    "yesterday's hits", "remember when", "flashback", "timeless", "evergreen",
    "best of", "greatest hits", "compilation", "collection", "anthology",
    "complete works", "discography", "catalog", "recordings", "sessions",
    "outtakes", "rare recordings", "premiere", "exclusive", "first listen",
    "new release", "single", "album track", "featured", "spotlight", "highlight",
    "popular", "trending", "viral", "hit", "chart-topper", "number one",
    "award winner", "grammy", "mtv award", "billboard", "hot 100", "charts",
    "top 10", "top 40", "radio friendly", "airplay", "rotation", "playlist favorite",
    "fan favorite", "crowd favorite", "audience choice", "vote winner",
    "contest winner", "competition", "battle of the bands", "talent show",
    "american idol", "x factor", "voice", "survivor", "apprentice", "big brother",
    "real housewives", "keeping up with the kardashians", "jersey shore",
    "geordie shore", "love island", "ex on the beach", "made in chelsea",
    "below deck", "sailor moon", "dragon ball z", "naruto", "pokemon",
    "south park", "family guy", "simpsons", "futurama", "rick and morty",
    "bojack horseman", "arrested development", "community", "parks and recreation",
    "brooklyn nine-nine", "the office", "parks and recreation", "modern family",
    "how i met your mother", "new girl", "veep", "silicon valley", "westworld",
    "game of thrones", "stranger things", "the crown", "bridgerton", "ozark",
    "narcos", "breaking bad", "better call saul", "the wire", "dexter", "six feet under",
    "the x-files", "buffy the vampire slayer", "angel", "firefly", "serenity",
    "star trek", "star wars", "marvel", "dc comics", "superhero", "comic book",
    "anime", "manga", "otaku", "weeb", "kawaii", "kyoto", "tokyo", "japan",
    "china", "korea", "asia", "eastern", "oriental", "far east", "pacific",
    "island", "beach", "summer", "vacation", "holiday", "travel", "adventure",
    "expedition", "exploration", "discovery", "quest", "mission", "task", "job",
    "work", "duty", "responsibility", "obligation", "commitment", "promise",
    "pledge", "oath", "swear", "vow", "marriage", "wedding", "divorce", "separation",
    "engagement", "dating", "romance", "love", "affection", "attraction", "desire",
    "lust", "passion", "intimacy", "sex", "gender", "male", "female", "intersex",
    "transgender", "non-binary", "queer", "lgbtq+", "identity", "orientation",
    "race", "ethnicity", "nationality", "citizenship", "passport", "visa", "border",
    "immigration", "emigration", "refugee", "asylum", "exile", "banishment",
    "punishment", "reward", "prize", "trophy", "medal", "certificate", "diploma",
    "degree", "qualification", "skill", "talent", "ability", "gift", "aptitude",
    "intelligence", "wisdom", "knowledge", "information", "data", "facts", "figures",
    "numbers", "statistics", "percentage", "ratio", "fraction", "decimal", "integer",
    "prime", "composite", "even", "odd", "positive", "negative", "zero", "infinity",
    "mathematics", "algebra", "geometry", "calculus", "trigonometry", "arithmetic",
    "logic", "reasoning", "argument", "proof", "theorem", "formula", "equation",
    "variable", "constant", "function", "graph", "coordinate", "axis", "point",
    "line", "angle", "shape", "area", "volume", "perimeter", "circumference",
    "radius", "diameter", "chord", "tangent", "secant", "arc", "sector", "segment",
    "cone", "cylinder", "sphere", "cube", "pyramid", "prism", "polyhedron",
    "polygon", "triangle", "square", "rectangle", "parallelogram", "rhombus",
    "trapezoid", "pentagon", "hexagon", "heptagon", "octagon", "nonagon", "decagon",
    "circle", "ellipse", "oval", "parabola", "hyperbola", "sine", "cosine",
    "tangent", "cotangent", "secant", "cosecant", "radian", "degree", "pi", "e",
    "logarithm", "exponent", "root", "square root", "cube root", "nth root",
    "factorial", "permutation", "combination", "probability", "statistics", "mean",
    "median", "mode", "range", "variance", "standard deviation", "distribution",
    "normal distribution", "bell curve", "skewed", "symmetric", "asymmetric",
    "frequency", "relative frequency", "cumulative frequency", "histogram", "bar graph",
    "line graph", "pie chart", "scatter plot", "box plot", "whisker plot",
    "stem and leaf plot", "dot plot", "table", "matrix", "vector", "scalar",
    "magnitude", "direction", "component", "unit vector", "dot product", "cross product",
    "scalar product", "tensor", "field", "space", "dimension", "manifold", "topology",
    "geometry", "algebra", "analysis", "number theory", "combinatorics", "graph theory",
    "set theory", "logic", "computability", "complexity", "algorithm", "data structure",
    "computer science", "programming", "software", "hardware", "network", "internet",
    "web", "website", "application", "app", "mobile app", "desktop app", "server",
    "client", "database", "SQL", "NoSQL", "relational", "non-relational", "schema",
    "table", "row", "column", "field", "key", "foreign key", "primary key",
    "index", "query", "transaction", "backup", "recovery", "security", "encryption",
    "decryption", "authentication", "authorization", "permission", "access control",
    "firewall", "malware", "virus", "worm", "trojan", "spyware", "adware", "ransomware",
    "phishing", "hacking", "cracking", "password", "username", "login", "logout",
    "sign in", "sign out", "register", "subscribe", "unsubscribe", "confirm",
    "verify", "validate", "authenticate", "authorize", "grant", "deny", "permit",
    "forbid", "allow", "enable", "disable", "activate", "deactivate", "start",
    "stop", "run", "execute", "launch", "initiate", "terminate", "kill", "abort",
    "cancel", "pause", "resume", "suspend", "restore", "reset", "restart", "reboot",
    "update", "upgrade", "downgrade", "install", "uninstall", "configure", "setup",
    "installation", "configuration", "settings", "preferences", "options", "menu",
    "interface", "GUI", "command line", "terminal", "shell", "script", "batch file",
    "executable", "binary", "source code", "compiler", "interpreter", "IDE",
    "editor", "debugger", "version control", "Git", "SVN", "repository", "branch",
    "merge", "commit", "push", "pull", "clone", "fork", "pull request", "merge request",
    "continuous integration", "CI", "continuous deployment", "CD", "pipeline",
    "automation", "testing", "unit test", "integration test", "end-to-end test",
    "QA", "quality assurance", "bug", "issue", "defect", "error", "exception",
    "crash", "hang", "freeze", "lag", "performance", "optimization", "efficiency",
    "speed", "latency", "throughput", "bandwidth", "memory", "RAM", "storage",
    "disk", "SSD", "HDD", "CPU", "GPU", "processor", "chip", "motherboard",
    "BIOS", "firmware", "driver", "plug-in", "extension", "add-on", "module",
    "library", "framework", "platform", "operating system", "OS", "Windows",
    "macOS", "Linux", "Ubuntu", "Debian", "CentOS", "Red Hat", "Android", "iOS",
    "Chrome OS", "FreeBSD", "OpenBSD", "NetBSD", "Solaris", "AIX", "HP-UX",
    "Unix", "POSIX", "kernel", "shell", "bash", "zsh", "fish", "PowerShell",
    "CMD", "DOS", "MS-DOS", "CP/M", "Apple DOS", "ProDOS", "GS/OS", "Classic Mac OS",
    "Mac OS X", "OS X", "macOS", "iOS", "iPadOS", "watchOS", "tvOS", "visionOS",
    "Android", "Android Wear", "Android TV", "Fire OS", "HarmonyOS", "鸿蒙", "鸿蒙系统",
    "Tizen", "webOS", "KaiOS", "Firefox OS", "Ubuntu Touch", "Sailfish OS",
    "Mer", "Nemo Mobile", "Plasma Mobile", "postmarketOS", "Maemo", "MeeGo",
    "Symbian", "Bada", "BlackBerry OS", "PCLinuxOS", "VectorLinux", "Peppermint OS",
    "Linux Lite", "elementary OS", "Zorin OS", "Solus", "Pop!_OS",
    "System76", "Ubuntu Studio", "Kubuntu", "Xubuntu", "Lubuntu", "Ubuntu Mate",
    "Ubuntu Budgie", "Ubuntu Kylin", "Ubuntu Core", "Ubuntu Touch", "Snappy",
    "Ubuntu Server", "Ubuntu Cloud", "Ubuntu for IoT", "Ubuntu for Raspberry Pi",
    "Ubuntu for OpenStack", "Ubuntu for Kubernetes", "Canonical", "Snapcraft",
    "snap", "flatpak", "appimage", "portable app", "portable executable", "PE",
    "ELF", "Mach-O", "COFF", "OMF", "a.out", "DOS executable", "COM file",
    "EXE file", "DLL file", "shared library", "dynamic library", "static library",
    "object file", "assembly language", "machine code", "binary code", "hexadecimal",
    "hex", "octal", "decimal", "binary", "bit", "byte", "kilobyte", "megabyte",
    "gigabyte", "terabyte", "petabyte", "exabyte", "zettabyte", "yottabyte",
    "kibibyte", "mebibyte", "gibibyte", "tebibyte", "pebibyte", "exbibyte",
    "zebibyte", "yobibyte", "bps", "kbps", "Mbps", "Gbps", "Tbps", "Pbps",
    "Ebbs", "Zbps", "Ybps", "Hertz", "Hz", "kHz", "MHz", "GHz", "THz", "PHz",
    "EHz", "ZHz", "YHz", "nanometer", "nm", "micrometer", "µm", "millimeter",
    "mm", "centimeter", "cm", "meter", "m", "kilometer", "km", "inch", "in",
    "foot", "ft", "yard", "yd", "mile", "mi", "nautical mile", "NM", "angstrom",
    "Å", "parsec", "pc", "light-year", "ly", "astronomical unit", "AU", "second",
    "s", "millisecond", "ms", "microsecond", "µs", "nanosecond", "ns", "picosecond",
    "ps", "femtosecond", "fs", "attosecond", "as", "zeptosecond", "zs", "yoctosecond",
    "ys", "minute", "min", "hour", "hr", "h", "day", "d", "week", "wk", "month",
    "mo", "year", "yr", "y", "decade", "century", "millennium", "eon", "epoch",
    "era", "period", "age", "time", "duration", "interval", "span", "stretch",
    "continuum", "timeline", "chronology", "history", "past", "present", "future",
    "now", "then", "soon", "later", "early", "late", "before", "after", "during",
    "while", "until", "since", "from", "to", "between", "among", "within", "without",
    "inside", "outside", "in", "out", "up", "down", "forward", "backward", "left",
    "right", "north", "south", "east", "west", "northeast", "northwest", "southeast",
    "southwest", "upstairs", "downstairs", "upward", "downward", "forward",
    "backward", "sideways", "horizontal", "vertical", "diagonal", "parallel",
    "perpendicular", "intersect", "cross", "meet", "touch", "contact", "connection",
    "junction", "intersection", "node", "vertex", "edge", "link", "bridge", "tunnel",
    "road", "street", "avenue", "boulevard", "lane", "drive", "highway", "freeway",
    "interstate", "route", "path", "trail", "track", "railroad", "railway", "subway",
    "metro", "underground", "tube", "monorail", "tram", "trolley", "bus", "taxi",
    "cab", "car", "vehicle", "automobile", "motor", "engine", "fuel", "gasoline",
    "diesel", "electric", "hybrid", "battery", "charging", "station", "parking",
    "garage", "tire", "wheel", "brake", "clutch", "transmission", "gear", "shift",
    "steering wheel", "horn", "light", "headlight", "taillight", "turn signal",
    "windshield", "window", "door", "seat", "seatbelt", "airbag", "dashboard",
    "speedometer", "odometer", "fuel gauge", "temperature gauge", "warning light",
    "check engine", "oil pressure", "coolant temperature", "battery voltage",
    "ABS", "ESP", "traction control", "cruise control", "GPS", "navigation",
    "infotainment", "radio", "stereo", "speaker", "microphone", "Bluetooth",
    "Wi-Fi", "wireless", "cellular", "mobile", "smartphone", "tablet", "laptop",
    "notebook", "netbook", "desktop", "tower", "monitor", "screen", "display",
    "resolution", "pixel", "refresh rate", "response time", "contrast ratio",
    "brightness", "color depth", "HDR", "SDR", "aspect ratio", "landscape",
    "portrait", "orientation", "rotation", "zoom", "pan", "scroll", "click",
    "double-click", "right-click", "left-click", "drag", "drop", "select",
    "highlight", "copy", "cut", "paste", "undo", "redo", "save", "save as",
    "open", "close", "new", "print", "find", "replace", "search", "filter",
    "sort", "group", "ungroup", "align", "justify", "indent", "outdent",
    "bullet", "numbering", "format", "style", "font", "size", "color", "bold",
    "italic", "underline", "strikethrough", "subscript", "superscript", "alignment",
    "left align", "center align", "right align", "justify align", "paragraph",
    "heading", "title", "subtitle", "caption", "label", "placeholder", "prompt",
    "input", "output", "entry", "field", "form", "button", "checkbox", "radio button",
    "dropdown", "list", "slider", "toggle", "switch", "progress bar", "spinner",
    "loading", "spinner", "animation", "transition", "effect", "fade", "slide",
    "zoom", "rotate", "scale", "transform", "translate", "skew", "perspective",
    "opacity", "visibility", "display", "position", "absolute", "relative",
    "fixed", "sticky", "static", "float", "clear", "overflow", "clip", "margin",
    "padding", "border", "outline", "box-sizing", "flexbox", "grid", "layout",
    "container", "item", "gap", "wrap", "flow", "order", "align", "justify",
    "align-items", "justify-content", "align-content", "flex-direction",
    "flex-wrap", "flex-flow", "flex-grow", "flex-shrink", "flex-basis",
    "grid-template-columns", "grid-template-rows", "grid-template-areas",
    "grid-auto-columns", "grid-auto-rows", "grid-auto-flow", "grid-column-start",
    "grid-column-end", "grid-row-start", "grid-row-end", "grid-column",
    "grid-row", "grid-area", "justify-items", "align-self", "justify-self",
    "place-content", "place-items", "place-self", "gap", "column-gap", "row-gap",
    "writing-mode", "direction", "unicode-bidi", "text-align", "text-decoration",
    "text-transform", "text-shadow", "letter-spacing", "word-spacing",
    "white-space", "word-break", "word-wrap", "line-height", "vertical-align",
    "list-style", "counter", "marker", "quotes", "content", "attr", "url",
    "image", "background", "background-image", "background-color", "background-repeat",
    "background-position", "background-size", "background-attachment",
    "background-origin", "background-clip", "border-image", "border-radius",
    "box-shadow", "filter", "backdrop-filter", "mix-blend-mode", "isolation",
    "z-index", "cursor", "pointer-events", "resize", "user-select", "touch-action",
    "overscroll-behavior", "scroll-behavior", "scroll-snap-type", "scroll-padding",
    "scroll-margin", "contain", "will-change", "appearance", "accent-color",
    "color-scheme", "forced-color-adjust", "text-orientation", "text-combine-upright",
    "ruby-align", "ruby-position", "hanging-punctuation", "hyphens", "line-break",
    "overflow-wrap", "tab-size", "text-justify", "text-outline", "text-fill-color",
    "text-stroke", "text-emphasis", "writing-mode", "text-orientation",
    "text-combine-upright", "text-emphasis-style", "text-emphasis-color",
    "text-emphasis-position", "ruby-align", "ruby-position", "hanging-punctuation",
    "hyphens", "line-break", "overflow-wrap", "tab-size", "text-justify",
    "text-outline", "text-fill-color", "text-stroke", "text-emphasis",
    "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation", "text-combine-upright", "ruby-align",
    "ruby-position", "hanging-punctuation", "hyphens", "line-break", "overflow-wrap",
    "tab-size", "text-justify", "text-outline", "text-fill-color", "text-stroke",
    "text-emphasis", "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation", "text-combine-upright", "ruby-align",
    "ruby-position", "hanging-punctuation", "hyphens", "line-break", "overflow-wrap",
    "tab-size", "text-justify", "text-outline", "text-fill-color", "text-stroke",
    "text-emphasis", "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation", "text-combine-upright", "ruby-align",
    "ruby-position", "hanging-punctuation", "hyphens", "line-break", "overflow-wrap",
    "tab-size", "text-justify", "text-outline", "text-fill-color", "text-stroke",
    "text-emphasis", "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation", "text-combine-upright", "ruby-align",
    "ruby-position", "hanging-punctuation", "hyphens", "line-break", "overflow-wrap",
    "tab-size", "text-justify", "text-outline", "text-fill-color", "text-stroke",
    "text-emphasis", "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation", "text-combine-upright", "ruby-align",
    "ruby-position", "hanging-punctuation", "hyphens", "line-break", "overflow-wrap",
    "tab-size", "text-justify", "text-outline", "text-fill-color", "text-stroke",
    "text-emphasis", "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation", "text-combine-upright", "ruby-align",
    "ruby-position", "hanging-punctuation", "hyphens", "line-break", "overflow-wrap",
    "tab-size", "text-justify", "text-outline", "text-fill-color", "text-stroke",
    "text-emphasis", "text-emphasis-style", "text-emphasis-color", "text-emphasis-position",
    "writing-mode", "text-orientation",......(lista muy larga cortada para brevedad)"
    // Agrega aquí todas tus palabras clave prohibidas, separadas por comas
    // Por brevedad, no se incluyen todas aquí, pero debes incluirlas todas
    // Asegúrate de que estén en minúsculas
].map(keyword => keyword.toLowerCase()); // Normaliza a minúsculas

/**
 * Filtra un array de items de búsqueda de YouTube basado en artistas permitidos y palabras prohibidas.
 * @param {Array} items - Array de items de respuesta de YouTube Search API.
 * @returns {Array} - Array de items filtrados.
 */
function filterMusic(items) {
  return items.filter(item => {
    const title = item.snippet.title.toLowerCase();
    const description = item.snippet.description ? item.snippet.description.toLowerCase() : '';
    const channelTitle = item.snippet.channelTitle.toLowerCase();

    // Combinar título, descripción y nombre del canal para la verificación
    const combinedText = `${title} ${description} ${channelTitle}`;

    // Verificar palabras prohibidas
    if (FORBIDDEN_KEYWORDS.some(keyword => combinedText.includes(keyword))) {
      console.log(`Filtrado por palabra prohibida: ${item.snippet.title}`);
      return false;
    }

    // Verificar si contiene un artista permitido
    // Busca coincidencias exactas de palabras enteras en el texto combinado
    let containsAllowedArtist = false;
    for (const artist of ALLOWED_ARTISTS) {
      // Usar expresiones regulares con límites de palabra \b para coincidencia exacta
      const regex = new RegExp(`\\b${artist}\\b`, 'i'); // 'i' para insensible a mayúsculas
      if (regex.test(combinedText)) {
        containsAllowedArtist = true;
        break; // Si encuentra uno, no necesita seguir buscando
      }
    }

    if (!containsAllowedArtist) {
      console.log(`Filtrado por artista no permitido: ${item.snippet.title}`);
      return false;
    }

    // Si pasa ambas verificaciones, incluirlo
    return true;
  });
}

// Exportar la función para usarla en otros archivos
module.exports = { filterMusic, ALLOWED_ARTISTS, FORBIDDEN_KEYWORDS }; // <-- Asegúrate de exportar ALLOWED_ARTISTS y FORBIDDEN_KEYWORDS también